# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4b783b0989f9f3ee946b3f70505c2c0907ec5e5e2a454d2b80e3e9f85cfeb078aa7ff780ee0e0507d8c1bf64ac426ba425b5d7631af47805d96bd646b83d48f

test:
  secret_key_base: 5e1c36ed02bd52a43b0dd2db81051e59004ad2436372353c8ffe10ec144e8d8a2c6a76fa9d00521fa68e086d3b79a9894ebbaec8198fdc6ff83a8327f1b25deb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
